dev.sh script to setup full dev environment in nix
fedimint/minimint pull request #245
Opened 2022-07-11 20:13 UTC by justinmoon

I found this little script very useful, myself. You get a full dev environment with:

```
$ nix-shell
$ source scripts/dev.sh
```

2022-07-11 20:32 UTC, dpc commented
Any reason why not to put it in `shellHook` directly?

2022-07-11 20:57 UTC, justinmoon commented
> Any reason why not to put it in `shellHook` directly?

I'm a complete nix noob, but if shell `shellHook` goes inside `shell.nix` then I imagine that might conflict with [how we run our integration tests](https://github.com/fedimint/minimint/blob/229c46110e715a81f703db806402c1808d372750/.github/workflows/rust.yml#L79)?

2022-07-11 21:05 UTC, dpc commented
That indeed might be the case. Potential solutions:

* detect CI run by checking some env variable
* At least with flakes it's possible to easily define multiple shells. With `nix-shell` it might require another file, which is not best.

2022-07-11 21:28 UTC, NicolaLS commented
> That indeed might be the case. Potential solutions:
> 
>     * detect CI run by checking some env variable (I just did `env FOO=bar nix develop` and can see it in the `export`'s output from the `shellHook` I've added).
> 
>     * At least with flakes it's possible to easily define multiple shells. With `nix-shell` it might require another file, which is not best.

This would be very cool but I think we should't hide to much stuff like this. What I mean is that a beginner who want's to contribute can just look at the bash scripts but might have no idea of how nix works and would't even notice that the shell hook is doing the magic

2022-07-11 21:34 UTC, dpc commented
That's fair. I don't understand the context here, so just wanted to point out that there's a possibility of getting things like that set up as a part of starting nix shell.

2022-07-11 21:42 UTC, NicolaLS commented
> That's fair. I don't understand the context here, so just wanted to point out that there's a possibility of getting things like that set up as a part of starting nix shell.

I guess you could argue that people who wan't to get into fedimint would need to learn nix basics anyway so maybe I don't really have a point..maybe do it with nix but point it out in the README that this is happening

2022-07-11 23:22 UTC, jkitman commented
You could potentially add parameters for the `FED_SIZE` and `PEG_IN_AMOUNT` then the `cli-test` and `latency-test` could be refactored to call this script.

Maybe just add a note to the `README` that developers can call the `dev.sh` script to run all the commands above.

2022-07-11 23:25 UTC, jkitman requested changes
You could potentially add parameters for the `FED_SIZE` and `PEG_IN_AMOUNT` then the `cli-test` and `latency-test` could be refactored to call this script.

Maybe just add a note to the `README` that developers can call the `dev.sh` script to run all the commands above.

2022-07-12 20:16 UTC, justinmoon commented
Closing in favor of #256

2022-07-12 20:16 UTC, closed without merging