Simplify Encodable impl for PublicKey
fedimint/minimint pull request #312
Opened 2022-07-30 10:32 UTC by justinmoon

@elsirion mentioned this during review for #269 but I forgot to update the PR

2022-08-03 11:42 UTC, elsirion requested changes
You can apply the same simplification to the `Decodable` side. Also the `shell.nix` change seems unrelated

2022-08-04 15:24 UTC, elsirion commented
Not sure what the CI failure is about, maybe needs a rebase after merging #311 ?

2022-08-04 17:15 UTC, justinmoon commented
CI failure is what https://github.com/fedimint/minimint/pull/319 tries to fix

2022-08-05 10:45 UTC, elsirion approved these changes

2022-08-05 10:45 UTC, merged